#Requires -Version 7.0

[CmdletBinding()]
param(
    [switch]$UpdateMigrationDoc,
    [switch]$CheckOnly
)

$ErrorActionPreference = 'Stop'
$repoRoot     = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$testFm       = Join-Path $PSScriptRoot 'Test-FrontMatter.ps1'
$versionsFile = Join-Path $PSScriptRoot 'product-versions.psd1'

$productVersions = Import-PowerShellDataFile -Path $versionsFile

function Compare-Version {
    param([string]$A, [string]$B)
    $pa = ($A -split '\.') | ForEach-Object { [int]$_ }
    $pb = ($B -split '\.') | ForEach-Object { [int]$_ }
    $len = [Math]::Max($pa.Length, $pb.Length)
    for ($i = 0; $i -lt $len; $i++) {
        $x = if ($i -lt $pa.Length) { $pa[$i] } else { 0 }
        $y = if ($i -lt $pb.Length) { $pb[$i] } else { 0 }
        if ($x -lt $y) { return -1 }
        if ($x -gt $y) { return  1 }
    }
    return 0
}

function Get-EffectiveStatus {
    param($FrontMatter, [string]$RelativePath)

    if (-not $RelativePath.StartsWith('src/')) { return 'legacy' }
    if (-not $FrontMatter) { return 'legacy' }

    $declared = [string]$FrontMatter.status
    if ($declared -eq 'deprecated') { return 'deprecated' }

    if ($FrontMatter.targets -is [System.Collections.IDictionary]) {
        foreach ($surface in $FrontMatter.targets.Keys) {
            $tested = [string]$FrontMatter.targets[$surface].tested_up_to
            $current = [string]$productVersions[$surface]
            if ($tested -and $current -and (Compare-Version $tested $current) -lt 0) {
                return 'stale'
            }
        }
    }
    return 'active'
}

function Get-GitSha {
    param([string]$AbsolutePath)
    try {
        $sha = (git -C $repoRoot hash-object -- $AbsolutePath 2>$null)
        return $sha.Trim()
    }
    catch { return $null }
}

# Walk paths.
$srcRoot = Join-Path $repoRoot 'src'
$legacyRoots = @('DVLS', 'RDM', 'Hub', 'custom_batch_actions') |
    ForEach-Object { Join-Path $repoRoot $_ } |
    Where-Object { Test-Path -LiteralPath $_ }

$srcFiles = if (Test-Path -LiteralPath $srcRoot) {
    Get-ChildItem -LiteralPath $srcRoot -Recurse -File -Include '*.ps1', '*.md' |
        Where-Object { $_.Name -ne 'README.md' }
} else { @() }

$legacyFiles = @()
foreach ($root in $legacyRoots) {
    $legacyFiles += Get-ChildItem -LiteralPath $root -Recurse -File -Include '*.ps1', '*.md' |
        Where-Object { $_.Name -ne 'README.md' }
}

$entries = New-Object System.Collections.Generic.List[psobject]
$problems = New-Object System.Collections.Generic.List[string]

foreach ($file in $srcFiles) {
    $relPath = [System.IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')
    $check = & $testFm -Path $file.FullName
    if (-not $check.Valid) {
        $problems.Add("$relPath`: $($check.Errors -join '; ')")
    }
    $effective = Get-EffectiveStatus -FrontMatter $check.FrontMatter -RelativePath $relPath
    $entries.Add([pscustomobject]@{
        path             = $relPath
        sha              = Get-GitSha -AbsolutePath $file.FullName
        effective_status = $effective
        frontmatter      = $check.FrontMatter
    })
}

foreach ($file in $legacyFiles) {
    $relPath = [System.IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')
    $entries.Add([pscustomobject]@{
        path             = $relPath
        sha              = Get-GitSha -AbsolutePath $file.FullName
        effective_status = 'legacy'
        frontmatter      = $null
    })
}

if ($CheckOnly) {
    if ($problems.Count -gt 0) {
        $problems | ForEach-Object { Write-Error -Message $_ -ErrorAction Continue }
        exit 1
    }
    Write-Host "All src/ files pass front-matter and version-gate checks."
    exit 0
}

# Emit catalog.json
$catalog = [pscustomobject]@{
    generated_at     = (Get-Date).ToString('o')
    product_versions = $productVersions
    entries          = $entries
}
$catalogJsonPath = Join-Path $repoRoot 'catalog.json'
$catalog | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $catalogJsonPath -Encoding utf8

# Emit CATALOG.md
$md = New-Object System.Text.StringBuilder
[void]$md.AppendLine('# Catalog')
[void]$md.AppendLine('')
[void]$md.AppendLine("Generated by ``tools/Build-Catalog.ps1``. Product versions: " +
    (($productVersions.GetEnumerator() | Sort-Object Name | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join ', ') + '.')
[void]$md.AppendLine('')

[void]$md.AppendLine('## Active samples')
[void]$md.AppendLine('')
$active = $entries | Where-Object { $_.effective_status -eq 'active' }
if (-not $active) {
    [void]$md.AppendLine('_None yet. New scripts land under `src/` via `/new-script`._')
}
else {
    $byGroup = $active | Group-Object { "$($_.frontmatter.product) / $($_.frontmatter.category)" }
    foreach ($g in $byGroup | Sort-Object Name) {
        [void]$md.AppendLine("### $($g.Name)")
        [void]$md.AppendLine('')
        [void]$md.AppendLine('| id | title | version | params |')
        [void]$md.AppendLine('|---|---|---|---|')
        foreach ($e in $g.Group | Sort-Object { $_.frontmatter.id }) {
            $paramList = if ($e.frontmatter.params) { ($e.frontmatter.params | ForEach-Object { $_.name }) -join ', ' } else { '' }
            [void]$md.AppendLine("| [``$($e.frontmatter.id)``]($($e.path)) | $($e.frontmatter.title) | $($e.frontmatter.script_version) | $paramList |")
        }
        [void]$md.AppendLine('')
    }
}

$stale = $entries | Where-Object { $_.effective_status -eq 'stale' }
if ($stale) {
    [void]$md.AppendLine('## Stale samples')
    [void]$md.AppendLine('')
    [void]$md.AppendLine('Declared `tested_up_to` falls below the current product version in `tools/product-versions.psd1`. Re-validate and bump.')
    [void]$md.AppendLine('')
    foreach ($e in $stale | Sort-Object path) {
        [void]$md.AppendLine("- [``$($e.path)``]($($e.path))")
    }
    [void]$md.AppendLine('')
}

[void]$md.AppendLine('## Legacy samples (pre-migration)')
[void]$md.AppendLine('')
[void]$md.AppendLine('See `MIGRATION.md` for the relocation campaign. These files remain at their original paths for downstream consumers.')
[void]$md.AppendLine('')
$legacy = $entries | Where-Object { $_.effective_status -eq 'legacy' } | Sort-Object path
foreach ($e in $legacy) {
    [void]$md.AppendLine("- [``$($e.path)``]($($e.path))")
}
[void]$md.AppendLine('')

$catalogMdPath = Join-Path $repoRoot 'CATALOG.md'
Set-Content -LiteralPath $catalogMdPath -Value $md.ToString() -Encoding utf8

Write-Host "Wrote $catalogMdPath and $catalogJsonPath. Active=$(($active | Measure-Object).Count), Stale=$(($stale | Measure-Object).Count), Legacy=$(($legacy | Measure-Object).Count)."

if ($UpdateMigrationDoc) {
    $migPath = Join-Path $repoRoot 'MIGRATION.md'
    if (-not (Test-Path -LiteralPath $migPath)) {
        Write-Warning "MIGRATION.md not found; skipping table update."
    }
    else {
        $migContent  = Get-Content -LiteralPath $migPath -Raw
        $markerStart = '<!-- BEGIN MIGRATION TABLE -->'
        $markerEnd   = '<!-- END MIGRATION TABLE -->'
        $idxStart    = $migContent.IndexOf($markerStart)
        $idxEnd      = $migContent.IndexOf($markerEnd)

        if ($idxStart -lt 0 -or $idxEnd -le $idxStart) {
            Write-Warning "Migration markers not found in MIGRATION.md — table not updated."
        }
        else {
            $sectionStart = $idxStart + $markerStart.Length
            $section      = $migContent.Substring($sectionStart, $idxEnd - $sectionStart)

            # Parse existing rows. Schema (6 columns):
            # legacy_path | target_src_path | intent | priority | migrated | notes
            $existingRows = [ordered]@{}
            foreach ($line in ($section -split "`r?`n")) {
                $trim = $line.Trim()
                if (-not $trim.StartsWith('|')) { continue }
                # Skip header and separator rows.
                if ($trim -match '^\|\s*legacy_path') { continue }
                if ($trim -match '^\|\s*-{2,}') { continue }
                $cells = $trim.Trim('|').Split('|') | ForEach-Object { $_.Trim() }
                if ($cells.Count -lt 6) { continue }
                $key = $cells[0].Trim('`').Trim()
                if (-not $key) { continue }
                $existingRows[$key] = [pscustomobject]@{
                    legacy_path     = $cells[0].Trim('`').Trim()
                    target_src_path = $cells[1].Trim('`').Trim()
                    intent          = $cells[2]
                    priority        = $cells[3]
                    migrated        = $cells[4]
                    notes           = $cells[5]
                }
            }

            # Build the set of legacy paths we observe on disk now.
            $observed = [ordered]@{}
            foreach ($e in $legacy | Sort-Object path) {
                $observed[$e.path] = $true
            }

            # Set of src/ paths declared active, for migrated computation.
            $activeSrcPaths = @{}
            foreach ($e in $active) { $activeSrcPaths[$e.path] = $true }

            # Compose rebuilt rows: union of (observed legacy files) and (rows already in table).
            # New observations get default intent/priority/notes; existing rows keep them.
            $allKeys = New-Object System.Collections.Generic.List[string]
            foreach ($k in $existingRows.Keys) { $allKeys.Add($k) }
            foreach ($k in $observed.Keys) {
                if (-not $existingRows.Contains($k)) { $allKeys.Add($k) }
            }

            $rowsOut = New-Object System.Collections.Generic.List[psobject]
            foreach ($k in ($allKeys | Sort-Object -Unique)) {
                $existing = if ($existingRows.Contains($k)) { $existingRows[$k] } else { $null }
                $defaultTarget = 'src/' + $k
                # Normalize Hub/Security → Hub/security case if no existing row says otherwise.
                if ($k -like 'Hub/Security/*') {
                    $defaultTarget = 'src/Hub/security/' + $k.Substring('Hub/Security/'.Length)
                }
                $target = if ($existing) { $existing.target_src_path } else { $defaultTarget }
                if (-not $target) { $target = $defaultTarget }

                $intent   = if ($existing -and $existing.intent)   { $existing.intent }   else { 'todo' }
                $priority = if ($existing -and $existing.priority) { $existing.priority } else { 'medium' }
                $notes    = if ($existing -and $existing.notes)    { $existing.notes }    else { '' }

                $migrated = if ($activeSrcPaths.ContainsKey($target)) { '☑' } else { '☐' }
                # Deprecated rows: by definition never get a src/ counterpart, so the box stays ☐.

                $stillExists = $observed.ContainsKey($k)
                if (-not $stillExists -and $intent -ne 'deprecated' -and $notes -notmatch 'file removed') {
                    $notes = if ($notes) { "$notes; (legacy file removed)" } else { '(legacy file removed)' }
                }

                $rowsOut.Add([pscustomobject]@{
                    legacy_path     = $k
                    target_src_path = $target
                    intent          = $intent
                    priority        = $priority
                    migrated        = $migrated
                    notes           = $notes
                })
            }

            $tableSb = [System.Text.StringBuilder]::new()
            [void]$tableSb.AppendLine('')
            [void]$tableSb.AppendLine('| legacy_path | target_src_path | intent | priority | migrated | notes |')
            [void]$tableSb.AppendLine('|---|---|---|---|---|---|')
            foreach ($r in $rowsOut) {
                [void]$tableSb.AppendLine("| ``$($r.legacy_path)`` | ``$($r.target_src_path)`` | $($r.intent) | $($r.priority) | $($r.migrated) | $($r.notes) |")
            }

            $newSection = $markerStart + $tableSb.ToString() + $markerEnd
            $updated = $migContent.Substring(0, $idxStart) + $newSection + $migContent.Substring($idxEnd + $markerEnd.Length)
            Set-Content -LiteralPath $migPath -Value $updated -Encoding utf8
            Write-Host "Refreshed migration table in MIGRATION.md ($($rowsOut.Count) rows)."
        }
    }
}
